### PyTorch Fundamentals

In [ ]:
import torch

print(torch.__version__)

2.4.1+cu121


## Introduction to Tensors

### Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7 ,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 69, 108], [54, 78, 123]]])

TENSOR

tensor([[[  1,   2,   3],
         [  3,  69, 108],
         [ 54,  78, 123]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[  1,   2,   3],
        [  3,  69, 108],
        [ 54,  78, 123]])

In [ ]:
TENSOR1 = torch.tensor([[[[1, 25, 69], [85, 47, 96], [78, 59, 63], [56, 89, 47], [45, 87, 104]]]])
TENSOR1

tensor([[[[  1,  25,  69],
          [ 85,  47,  96],
          [ 78,  59,  63],
          [ 56,  89,  47],
          [ 45,  87, 104]]]])

In [ ]:
TENSOR1.ndim

4

In [ ]:
TENSOR1.shape

torch.Size([1, 1, 5, 3])

In [ ]:
TENSOR1[0]

tensor([[[  1,  25,  69],
         [ 85,  47,  96],
         [ 78,  59,  63],
         [ 56,  89,  47],
         [ 45,  87, 104]]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers
to better represent the data.

# Start with random numbers --> look at data --> update random numbers  -->     look at data --> update random numbers

In [ ]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8310, 0.2236, 0.2028, 0.0414],
        [0.0768, 0.3014, 0.5200, 0.9413],
        [0.1231, 0.1919, 0.4221, 0.2944]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size= (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-28-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

 Note:  Tensor datatypes is  one of the 3 errors  you 'll run into Pytorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not  right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                                device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half) # or torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Int 32 tensor
int_32_tensor = torch.tensor([3, 6, 8], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 72.])

### Getting information from tensors (Tensors attributes)

1. Tensors not right datatype - to get datatype from a tensor , can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor , can use  `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0428, 0.7900, 0.6709, 0.7292],
        [0.0326, 0.0535, 0.4039, 0.4994],
        [0.5438, 0.7521, 0.3163, 0.4038]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype} ")
print(f"Shape of tensor: {some_tensor.shape} ")
print(f"device tensor is on: {some_tensor.device} ")

tensor([[0.0428, 0.7900, 0.6709, 0.7292],
        [0.0326, 0.0535, 0.4039, 0.4994],
        [0.5438, 0.7521, 0.3163, 0.4038]])
Datatype of tensor: torch.float32 
Shape of tensor: torch.Size([3, 4]) 
device tensor is on: cpu 


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
*  Divison
* Matrix multiplication



In [ ]:
# Create a Tensor and add 1000 to it
tensor = torch.tensor([1, 2, 3])
tensor + 1000

tensor([1001, 1002, 1003])

In [ ]:
# Multiply a Tensor by 10
tensor =tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
tensor


tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor = tensor - 10
tensor

tensor([ 0, 10, 20])

In [ ]:
# Try out Pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([  0, 100, 200])

In [ ]:
torch.add(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two  main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The ** inner dimensions ** must matchh:
* `(3, 2) @ (3, 2)` won't work
* `(8, 9) @ (9, 8)` will work

2. The resulting matrix has the shape of the ** outer dimensions **:
* `(2, 3) @ (3, 2)` --> `(2, 2)`
* `(3, 2) @ (2, 3)` --> `(3, 3)`


In [ ]:
# Element-wise multiplication
print(tensor, " * ", tensor)
print(f"Equals: {tensor * tensor}")

tensor([ 0, 10, 20])  *  tensor([ 0, 10, 20])
Equals: tensor([  0, 100, 400])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(500)

In [ ]:
# Matrix multiplication using @ symbol
tensor @ tensor

tensor(500)

In [ ]:
tensor

tensor([ 0, 10, 20])

In [ ]:
# Matrix multiplication by hand
0*0 + 10*10 + 20*20

500

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(500)
CPU times: user 2.34 ms, sys: 0 ns, total: 2.34 ms
Wall time: 2.33 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 64 µs, sys: 11 µs, total: 75 µs
Wall time: 78.9 µs


tensor(500)

### One of the most common errors in deep learning : shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B)  # torch.mm is the same as torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of given tensor.

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Orginal shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying:  {tensor_A.shape} @ {tensor_B.T.shape}  <-- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Orginal shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying:  torch.Size([3, 2]) @ torch.Size([2, 3])  <-- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

## finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean  - note: the torch.mean() function requires an tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [ ]:
y = torch.arange(1, 100, 10)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() --> returns index position of target tensor where the minimum value occurs
torch.argmin(y), y.argmin()

(tensor(0), tensor(0))

In [ ]:
y[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax() --> returns index position of target tensor where the maximum value occurs
torch.argmax(y), y.argmax()

(tensor(9), tensor(9))

In [ ]:
y[9]

tensor(91)


## Reshaping , Stacking, Squeezing and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain sahpe but keep the same memory as the original tensor
* Stacking -  combine multiple tensors on top of each other(vstack) or side by side(hsatck)
* Squeeze  - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Reurn a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped , x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same#e memory as  the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#  Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 874596
x_original[0, 0, 0] , x_permuted[0, 0, 0]

(tensor(874596.), tensor(874596.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0][0][1], x[0][0][2]

(tensor(1), tensor(2), tensor(3))

In [ ]:
# Extracting the middle element
x[0][1][1]

tensor(5)

In [ ]:
# Index on x to return 9
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of the 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1th dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in Pytorch tensor --> `torch.from_numpy(ndarray)`
* PyTorch tensor --> NumPy --> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # warning: when converting from numpy --> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of array, what will this  do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor =  tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happpens to `numpy_tensor`?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how  a neural network learns:

`start with random numbers --> tensor operations --> update random numbers to try and make them better representations od data -->again and again and again....`

To reduce the randomness in neural networks and Pytorch comes the concept of a   **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0081, 0.5502, 0.6030, 0.9528],
        [0.1766, 0.4054, 0.3071, 0.1007],
        [0.0658, 0.0187, 0.3064, 0.9913]])
tensor([[0.1145, 0.8869, 0.9060, 0.1984],
        [0.9005, 0.0289, 0.5446, 0.5372],
        [0.4466, 0.8122, 0.1106, 0.5507]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA  + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory(good, fine).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use  your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...  , see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

for 2, 3 Pytorch + GPU drivers(CUDA) takes a little bit of setting up, to do this, refer to Pytorch setup documentation: https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Sun Oct  6 11:28:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

   The reason we want our tensors/models on the GPU is because using a GPU resuts in faster computations.

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
## If tensor is on GPU , can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])