In [26]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)


    return out

In [27]:
# create dataset
features = torch.rand(10,5) # 10 rows and 5 cols

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5208],
        [0.5285],
        [0.5183],
        [0.5381],
        [0.5247],
        [0.5355],
        [0.5184],
        [0.5022],
        [0.5153],
        [0.5297]], grad_fn=<SigmoidBackward0>)

In [28]:
# show model weights and bias
model.network[0].bias, model.network[0].weight

(Parameter containing:
 tensor([ 0.2023,  0.1237, -0.4132], requires_grad=True),
 Parameter containing:
 tensor([[-0.4385, -0.4203,  0.3925,  0.0482,  0.1326],
         [-0.0457, -0.3041,  0.3619, -0.4437,  0.3956],
         [-0.2954, -0.3619,  0.3667,  0.4067,  0.3430]], requires_grad=True))

In [29]:
!pip install torchinfo

In [30]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00