In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
print(a)

tensor([[3.8733e-37, 0.0000e+00, 9.6578e+02],
        [4.4474e-41, 1.4013e-45, 1.2612e-44]])


In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
# using rand
torch.rand(2,3)  # generates floating values between 0 and 1

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.4831, 0.6171, 0.1010],
        [0.4062, 0.7812, 0.1300]])

In [11]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]]) # Creating custom tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))  # identity matrix

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)  # same shape tensor

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 4050196424303993700]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [25]:
# find data type
x.dtype

torch.int64

In [26]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [29]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [30]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

### 2. Element wise operation

In [31]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [33]:
# add
a + b
# # sub
a - b
# # multiply
a * b
# # division
a / b
# # power
a ** b
# # mod
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [34]:
c = torch.tensor([1, -2, 3, -4])

In [35]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [36]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [37]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [38]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [39]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [40]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [41]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [42]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [44]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [45]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [46]:
# median
torch.median(e)

tensor(4.)

In [47]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [48]:
# product
torch.prod(e)

tensor(0.)

In [49]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [50]:
# variance
torch.var(e)

tensor(9.8667)

In [51]:
# argmax
torch.argmax(e)

tensor(3)

In [52]:
# argmin
torch.argmin(e)

tensor(5)

### 4. Matrix operations

In [53]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [54]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [55]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [56]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [58]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [59]:
# determinant
torch.det(h)

tensor(-315.)

In [60]:
# inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

### 5. Comparison operations

In [61]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [63]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[False,  True,  True],
        [False, False, False]])

### 6. Special functions

In [64]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [65]:
# log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [66]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [67]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [68]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [69]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [70]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

## Inplace Operations

In [71]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [72]:
m.add_(n)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [73]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [74]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [75]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [76]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [77]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

## Copying a Tensor

In [78]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [79]:
b = a

In [80]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [81]:
a[0][0] = 0

In [82]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [84]:
b # Copied version also gets changed

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [85]:
id(a)

136318394770320

In [86]:
id(b)

136318394770320

In [87]:
b = a.clone()

In [88]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [89]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [90]:
a[0][0] = 10

In [91]:
a

tensor([[10.0000,  0.8935,  0.0497],
        [ 0.1780,  0.3011,  0.1893]])

In [97]:
b # now no changes in copied version

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [98]:
id(a)

136318394770320

In [99]:
id(b)

136314426349456

In [101]:
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on cpu
matrix_cpu_1 = torch.rand(size, size)
matrix_cpu_2 = torch.rand(size, size)

# Measure time for matrix multiplication on cpu
start_time_cpu = time.time()
result_cpu = torch.matmul(matrix_cpu_1, matrix_cpu_2)
end_time_cpu = time.time() - start_time_cpu

print(f"Time taken for matrix multiplication on CPU: {end_time_cpu:.4f} seconds")

# Move matrices on GPU
matrix_gpu_1 = matrix_cpu_1.to('cuda')
matrix_gpu_2 = matrix_cpu_2.to('cuda')

# Measure time for matrix multiplication on gpu
start_time_gpu = time.time()
result_gpu = torch.matmul(matrix_gpu_1, matrix_gpu_2)
torch.cuda.synchronize()  # Wait for the GPU operation to complete
end_time_gpu = time.time() - start_time_gpu

print(f"Time taken for matrix multiplication on GPU: {end_time_gpu:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", end_time_cpu / end_time_gpu)


Time taken for matrix multiplication on CPU: 24.6230 seconds
Time taken for matrix multiplication on GPU: 0.5413 seconds

Speedup (CPU time / GPU time): 45.48542549349494


# Reshaping Tensors

In [106]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [107]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [108]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
b = torch.rand(2,3,4)
b


tensor([[[0.9200, 0.0472, 0.5397, 0.7160],
         [0.2801, 0.6461, 0.9829, 0.0332],
         [0.6062, 0.9161, 0.5627, 0.7324]],

        [[0.0059, 0.0328, 0.6305, 0.4399],
         [0.6325, 0.2586, 0.8932, 0.1828],
         [0.9434, 0.3875, 0.5627, 0.6529]]])

In [110]:
# permute
b.permute(2,0,1) # (2, 3, 4) ---> (4, 2, 3)

tensor([[[0.9200, 0.2801, 0.6062],
         [0.0059, 0.6325, 0.9434]],

        [[0.0472, 0.6461, 0.9161],
         [0.0328, 0.2586, 0.3875]],

        [[0.5397, 0.9829, 0.5627],
         [0.6305, 0.8932, 0.5627]],

        [[0.7160, 0.0332, 0.7324],
         [0.4399, 0.1828, 0.6529]]])

In [113]:
c = torch.rand(226,226,3)


In [114]:
# unsqueeze
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [115]:
d = torch.rand(1,20)
d

tensor([[0.7229, 0.5152, 0.8557, 0.9449, 0.9491, 0.8092, 0.7189, 0.8853, 0.8272,
         0.3258, 0.5009, 0.4610, 0.1566, 0.0176, 0.9159, 0.6931, 0.3279, 0.1297,
         0.4820, 0.4417]])

In [116]:
# squeeze
d.squeeze()

tensor([0.7229, 0.5152, 0.8557, 0.9449, 0.9491, 0.8092, 0.7189, 0.8853, 0.8272,
        0.3258, 0.5009, 0.4610, 0.1566, 0.0176, 0.9159, 0.6931, 0.3279, 0.1297,
        0.4820, 0.4417])

# Numpy and PyTorch

In [117]:
import numpy as np

In [118]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [119]:
b = a.numpy()

In [120]:
type(b)

numpy.ndarray

In [121]:
c = np.array([1, 2, 6])
c

array([1, 2, 6])

In [122]:
torch.from_numpy(c)

tensor([1, 2, 6])